Battery in: Batterie in
Battery out: Batterie out
Battery: Batterie
Biomass GT: Biomass GT
Biomass ST: Biomass ST
Biomass: Biomasse
CH4 Backpressure CHP: CH4 Backpressure CHP
CH4 Boiler: CH4 Boiler
CH4 Excess: CH4 Excess
CH4 Extraction CHP: CH4 Extraction CHP
CH4 GT: CH4 GT
CH4: CH4
Curtailment: Curtailment
El. demand: El. demand
El. in: Batterie in
Electrolyzer: Electrolyzer
H2 GT: H2 GT
Hard coal: Steinkohle
Heat demand: Heat demand
Heat Excess: Heat Excess
Heat Storage: Heat Storage
Hydro reservoir: Reservoir
Hydro ROR: Hydro ROR
Lignite: Braunkohle
Nuclear ST: Nuclear ST
Oil: Öl
Other: Andere
PV: PV
res. PtH: res. PtH
Shortage: Shortage
Transmission: Transmission
Wind off: Wind off
Wind on: Wind on