biomass-gt: Biomass GT
biomass-st: Biomass ST
ch4-boiler: CH4 Boiler
ch4-bpchp: CH4 Backpressure CHP
ch4-extchp: CH4 Extraction CHP
ch4-gt: CH4 GT
electricity-curtailment: Curtailment
electricity-demand: El. demand
electricity-electrolyzer: Electrolyzer
electricity-liion_battery: Battery
electricity-pth: res. PtH
electricity-shortage: Shortage
electricity-transmission: Transmission
h2-gt: H2 GT
heat_central-demand: Heat cen. demand
heat_decentral-demand: Heat dec. demand
hydro-ror: Hydro ROR
solar-pv: PV
wind-onshore: Wind on
h2-bpchp: H2 Backpressure CHP
ch4-excess: CH4 excess
ch4-demand: CH4 demand
ch4-shortage: CH4 shortage
heat_central-excess: Heat cen. excess
heat_central-storage: Heat cen. storage
heat_central-shortage: Heat cen. shortage
heat_decentral-excess: Heat dec. excess
heat_decentral-storage: Heat dec. storage
heat_decentral-shortage: Heat dec. shortage
m_reactor-storage_products: Methanation
